# Form implementation generated from reading ui file 'new_task.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow, QMessageBox, QTimeEdit
from __supporting_func import FrameLess
from PyQt6.QtCore import Qt
from _Date_Screen import _Date
from PyQt6.QtCore import Qt, pyqtSignal, QDate, QTime
from __Backend import ExcelTaskManager
import time
from threading import Thread
# from __Backend import Create_Task

class Date_Screen(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = _Date()
        self.ui.setupUi(self)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)
        FrameLess(self)
    

class _View_Task(object):
    def __init__(self, data=["Gym", "", "2023-09-23", "12:00 Pm", "google.com"]):
        print("Inside", data)
        self.data = data
        self.dataSet = {}
        self.ex1 = ExcelTaskManager("./resources/Tasks.xlsx")
        self.ex2 = ExcelTaskManager("./resources/completed.xlsx")

    def open_second_window(self):
        self.second_window = Date_Screen()
        self.second_window.show()

        def date_check():
            while self.second_window.ui.date == {"Result":[False, None]}:
                time.sleep(2)
            val = self.second_window.ui.date
            if val["Result"][0] == True: self.select_date_btn.setText(val["Result"][1])
            print("outside1:", self.second_window.ui.date)

        self.Time_Thread = Thread(target=lambda: date_check())
        self.Time_Thread.daemon = True
        self.Time_Thread.start()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 500)
        Form.setStyleSheet("background-color: transparent;")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(770, 500))
        Form.setMaximumSize(QtCore.QSize(770, 500))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 770, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(770, 500))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/View_Task.png"))
        self.label.setObjectName("label")
        self.Input_User_Task = QtWidgets.QTextEdit(parent=Form)
        self.Input_User_Task.setGeometry(QtCore.QRect(90, 120, 390, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_User_Task.sizePolicy().hasHeightForWidth())
        self.Input_User_Task.setSizePolicy(sizePolicy)
        self.Input_User_Task.setMinimumSize(QtCore.QSize(390, 30))
        self.Input_User_Task.setMaximumSize(QtCore.QSize(390, 30))
        self.Input_User_Task.setStyleSheet("background-color:transparent;\n"
        "outline:none;\n"
        "border:none;\n"
        "font-size:12pt")
        self.Input_User_Task.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Input_User_Task.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Input_User_Task.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Input_User_Task.setTabChangesFocus(False)
        self.Input_User_Task.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.Input_User_Task.setLineWrapColumnOrWidth(0)
        self.Input_User_Task.setObjectName("Input_User_Task")
        self.Input_User_Task_Des = QtWidgets.QPlainTextEdit(parent=Form)
        self.Input_User_Task_Des.setGeometry(QtCore.QRect(90, 210, 391, 171))
        self.Input_User_Task_Des.setStyleSheet("background-color:transparent;\n"
        "border:none;\n"
        "font-size:11pt;\n"
        "color:gray;")
        self.Input_User_Task_Des.setObjectName("Input_User_Task_Des")

        # Date Selection
        self.select_date_btn = QtWidgets.QPushButton(parent=Form)
        self.select_date_btn.setGeometry(QtCore.QRect(530, 126, 75, 23))
        self.select_date_btn.clicked.connect(self.open_second_window)
        self.select_date_btn.setStyleSheet("background-color:transparent;\n"
        "color:gray;\n"
        "font-size:10pt;\n")
        self.select_date_btn.setObjectName("select_date_btn")
        self.Input_url = QtWidgets.QTextEdit(parent=Form)
        self.Input_url.setGeometry(QtCore.QRect(530, 240, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_url.sizePolicy().hasHeightForWidth())
        self.Input_url.setSizePolicy(sizePolicy)
        self.Input_url.setMinimumSize(QtCore.QSize(150, 25))
        self.Input_url.setMaximumSize(QtCore.QSize(150, 25))
        self.Input_url.setStyleSheet("background-color:transparent;\n"
        "outline:none;\n"
        "border:none;\n"
        "font-size:10pt")
        self.Input_url.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Input_url.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Input_url.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Input_url.setTabChangesFocus(False)
        self.Input_url.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.Input_url.setLineWrapColumnOrWidth(0)
        self.Input_url.setObjectName("Input_url")


        def Complete_Task():
            def update_files():
                self.ex1.open_excel_file()
                self.ex1.remove_data(self.data[0])
                self.ex1.save_excel_file()
                # fileName = "./resources/completed.xlsx"
                # ex2 = ExcelTaskManager(fileName)
                if not self.ex2.check_excel_file_existence():
                    self.ex2.create_excel_file()
                self.ex2.write_data(self.data)
                self.ex2.save_excel_file()
                # ex2 = ExcelTaskManager("./resources/Tasks.xlsx")
            modification_thread = Thread(target=lambda: update_files())
            modification_thread.daemon = True
            modification_thread.start()
            self.dataSet = {"complete":self.data}
            Form.close()
        
        def Delete_Task():
            def update_files():
                self.ex1.open_excel_file()
                self.ex1.remove_data(self.data[0])
                self.ex1.save_excel_file()
                
            name = self.Input_User_Task.toPlainText()
            if name == " " or name == "":
                popup = QMessageBox()
                popup.setWindowTitle("Invalid Data Entered")
                popup.setText("Task Name not be Empty ...")
                popup.setIcon(QMessageBox.Icon.Information)
                popup.setStandardButtons(QMessageBox.StandardButton.Ok)
                popup.exec()
            else:
                modification_thread = Thread(target=lambda: update_files())
                modification_thread.daemon = True
                modification_thread.start()
                self.dataSet = {"delete":self.data}
                Form.close()
        
        def Update_Task():
            name, des = self.Input_User_Task.toPlainText(), self.Input_User_Task_Des.toPlainText(), 
            date, time, url = self.select_date_btn.text(),  self.timeEdit.text(), self.Input_url.toPlainText()
            
            def update_files():
                fileName = "./resources/Tasks.xlsx"
                ex1, ex2 = ExcelTaskManager(fileName), ExcelTaskManager(fileName)
                ex1.remove_data(self.data[0])
                ex1.save_excel_file()
                ex2.write_data([name, des, date, time, url])
                ex2.save_excel_file()
                del ex1
                del ex2
                
            name, date = self.Input_User_Task.toPlainText(), self.select_date_btn.text()
            if (name == " " or name == "") or date=="Select Date" or "Select" in date:
                popup = QMessageBox()
                popup.setWindowTitle("Invalid Data Entered")
                popup.setText("Task Name and Date not be NULL")
                popup.setIcon(QMessageBox.Icon.Information)
                popup.setStandardButtons(QMessageBox.StandardButton.Ok)
                popup.exec()
            else:
                modification_thread = Thread(target=lambda: update_files())
                modification_thread.daemon = True
                modification_thread.start()
                
                self.dataSet = {"update":[self.data, [name, des, date, time, url]]}
                Form.close()
                

        self.complete_btn = QtWidgets.QPushButton(parent=Form)
        self.complete_btn.setGeometry(QtCore.QRect(645, 442, 91, 23))
        self.complete_btn.setStyleSheet("background-color:transparent;\n"
        "font-size:11pt;\n"
        "font-weight:bold;\n"
        "font-family:Arial;")
        self.complete_btn.setObjectName("complete_btn")
        self.complete_btn.clicked.connect(lambda: Complete_Task())


        self.delete_btn = QtWidgets.QPushButton(parent=Form)
        self.delete_btn.setGeometry(QtCore.QRect(530, 442, 91, 23))
        self.delete_btn.clicked.connect(Form.close)
        self.delete_btn.setStyleSheet("background-color:transparent;\n"
        "font-size:11pt;\n"
        "font-weight:bold;\n"
        "font-family:Arial;")
        self.delete_btn.setObjectName("delete_btn")
        self.delete_btn.clicked.connect(lambda: Delete_Task())
        
        
        self.update_btn = QtWidgets.QPushButton(parent=Form)
        self.update_btn.setGeometry(QtCore.QRect(415, 443, 91, 23))
        self.update_btn.clicked.connect(Form.close)
        self.update_btn.setStyleSheet("background-color:transparent;\n"
        "font-size:11pt;\n"
        "font-weight:bold;\n"
        "font-family:Arial;")
        self.update_btn.setObjectName("update_btn")
        self.delete_btn.clicked.connect(lambda: Update_Task())
        
        self.cancel_btn = QtWidgets.QPushButton(parent=Form)
        self.cancel_btn.setGeometry(QtCore.QRect(300, 443, 91, 23))
        self.cancel_btn.clicked.connect(Form.close)
        self.cancel_btn.setStyleSheet("background-color:transparent;\n"
        "font-size:11pt;\n"
        "font-weight:bold;\n"
        "font-family:Arial;")
        self.cancel_btn.setObjectName("cancel_btn")
        
        
        self.timeEdit = QtWidgets.QTimeEdit(parent=Form)
        self.timeEdit.setGeometry(QtCore.QRect(530, 180, 151, 22))
        self.timeEdit.setStyleSheet("background-color:transparent;\n"
        "color:gray;\n"
        "font-size:10pt;\n"
        "border:none;")
        
        self.timeEdit.setObjectName("timeEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        
        print(self.data)
        self.Input_User_Task.setText(self.data[0])
        self.Input_User_Task_Des.setPlainText(self.data[1])
        self.select_date_btn.setText(self.data[2])
        
        self.timeEdit.setDisplayFormat("hh:mm AP")
        time_hour, time_min = self.data[3].split(":")[0], self.data[3].split(":")[1].split(" ")[0]
        time_data = QTime(int(time_hour), int(time_min))
        self.timeEdit.setTime(time_data)
        self.Input_url.setText(self.data[4])
        
        self.Input_User_Task.setPlaceholderText(_translate("Form", "Enter your task ..."))
        self.Input_User_Task_Des.setPlaceholderText(_translate("Form", "Type your task info ..."))
        # self.select_date_btn.setText(_translate("Form", "Select Date"))
        self.Input_url.setPlaceholderText(_translate("Form", "Enter your task name ..."))
        
        self.complete_btn.setText(_translate("Form", "Complete"))
        self.delete_btn.setText(_translate("Form", "Delete"))
        self.update_btn.setText(_translate("Form", "Update"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = _View_Task()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
